"""Initialize tables

Revision ID: eb5e757854eb
Revises: 
Create Date: 2025-05-23 03:56:01.610521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5e757854eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ria_card_links',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ERROR', 'PROCEED', 'NEW', 'DEAD', name='parsestatus'), nullable=False),
    sa.Column('is_under_delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('ria_cards',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price_usd', sa.Integer(), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('images_count', sa.Integer(), nullable=False),
    sa.Column('car_number', sa.String(), nullable=True),
    sa.Column('car_vin', sa.String(), nullable=True),
    sa.Column('datetime_found', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('ria_errors',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ERROR', 'PROCEED', 'NEW', 'DEAD', name='parsestatus'), nullable=False),
    sa.Column('link_type', sa.Enum('PAGE_LINK', 'CARD', name='linktype'), nullable=False),
    sa.Column('count_retries', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('is_under_delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ria_errors')
    op.drop_table('ria_cards')
    op.drop_table('ria_card_links')
    # ### end Alembic commands ###
